runtime: nodejs20 # 사용하고 있는 Node.js 버전
env: standard # 표준환경 (flex: 플렉시블 환경)

# 인스턴스 클래스 및 자동 확장 설정
instance_class: F2 # 기본 인스턴스 클래스
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5 # 동시에 실행될 수 있는 최대 인스턴스 수

# 애플리케이션이 실행될 기본 핸들러
handlers:
  - url: /public
    static_dir: public

  - url: /.*
    script: auto # app.js 또는 server.js 로 라우팅되도록

# 환경 변수 설정
env_variables:
  NODE_ENV: "production"
  PORT: "8080" # 구글 app engine 에서 사용되는 8080 포트
  GOOGLE_CLOUD_PROJECT: "your-project-id"
# 배포 명령어 : gcloud app deploy
